version: "3"
services:
  wiki:
    container_name: "__CONTAINER____wiki"
    image: requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: __DB_PASSWORD_REPLACE_ME__
      DB_NAME: wiki
      TZ: "Europe/Berlin"
    restart: unless-stopped
    networks:
      - default
      - caddy
  db:
    container_name: "__CONTAINER____db"
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: __DB_PASSWORD_REPLACE_ME__
      POSTGRES_USER: wikijs
    restart: unless-stopped
    networks:
      - default
    volumes:
      - ./data/database:/var/lib/postgresql/data
networks:
  default:
    external: false
  caddy:
    external: true